### ISSUE TITLE
Path specification query

### ISSUE THREAD

**Issue by RahamaTahir** [Raghav714/EEG-Emotion-classification#1]
i have some queries regarding your git hub EEG-Emotion-classification code  https://github.com/Raghav714/EEG-Emotion-classification  . I have run your code and got the error at this line in load_deap.py file.
fname = "/data_preprocessed_python/data_preprocessed_python/s"+str(name)+".dat"
x = pickle.load(open(fname, 'rb'))
The error is which i am getting is:
File "C:/Users/Rahama Tahir/Desktop/new/EEG-Emotion-classification/load_deap.py", line 19, in <module>
    x = pickle.load(open(fname, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/data_preprocessed_python/data_preprocessed_python/s01.dat'
Can you please help me out with this. By explaining it in more detail, how to exactly make it run and what are you trying to store in fname. I am using Pycharm to run your files. 
Kindly help me out it would be of great help

**Comment by chihhsinglin** [comment]
Hi Raghav714
I have the same issue for regarding your git hub EEG-Emotion-classification code https://github.com/Raghav714/EEG-Emotion-classification . I have run your code and got the error at this line in load_deap.py file.
fname = "/data_preprocessed_python/data_preprocessed_python/s"+str(name)+".dat"
x = pickle.load(open(fname, 'rb'))
The error is which i am getting is:
Traceback (most recent call last):
  File "load_deap.py", line 19, in <module>
    x = pickle.load(open(fname, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/c/Users/Chih-Hsing Lin/Downloads/EEG-Emotion-classification-master/s01.dat'

Can you please help me out with this. By explaining it in more detail, how to exactly make it run and what are you trying to store in fname. I am using Git Bash to run your files.
Kindly help me out it would be of great help

**Comment by Saumyadav** [comment]
> 

Can you help with this issue?

**Comment by Mediel007** [comment]
Hi Raghav714 @Raghav714 
I have the same issue for regarding your git hub EEG-Emotion-classification code https://github.com/Raghav714/EEG-Emotion-classification . I have run your code and got the error at this line in load_deap.py file.
fname = "/data_preprocessed_python/data_preprocessed_python/s"+str(name)+".dat"
x = pickle.load(open(fname, 'rb'))
The error is which i am getting is:
Traceback (most recent call last):
File "load_deap.py", line 19, in
x = pickle.load(open(fname, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/c/Users/Chih-Hsing Lin/Downloads/EEG-Emotion-classification-master/s01.dat'

Can you please help me out with this. By explaining it in more detail, how to exactly make it run and what are you trying to store in fname. I am using Git Bash to run your files.
Kindly help me out it would be of great help

**Comment by azharyaseennj7** [comment]
Hi Raghav714 @Raghav714 
I have an issue regarding your git hub EEG-Emotion-classification code https://github.com/Raghav714/EEG-Emotion-classification . I have run your code and got the error in load_deap.py file.
The error is which i am getting is
FileNotFoundError: [Errno 2] No such file or directory. I'm attaching the screenshot of error. PFB

Could you you please help me out with this. By explaining it in more detail, how to exactly make it run and what are you trying to store in fname. I am using VS Code to run your files.
Kindly help me out it would be of great help
![Screenshot (55)](https://user-images.githubusercontent.com/62641857/211514765-8c091cdf-2c98-4b93-ab2f-a97d63968320.png)

Regards,
Azhar Yaseen N J
azharyaseennj7@gmail.com
